import LogoSvg from "@/assets/svgs/LogoSvg";
import {
  IoChatbubbleEllipsesOutline,
  IoPeopleOutline,
  IoTrophyOutline,
} from "react-icons/io5";
import CustomLink from "@/components/atoms/CustomLink";
import ProviderBtns from "@/components/atoms/ProviderBtns";
import Text from "@/components/atoms/Test";
import { SignupForm } from "@/components/molicuses/SignUpForm";

export const metadata = {
  title: "Sign Up | Devate Arena",
  description: "Generated by create next app",
};

const SignupPage = () => {
  return (
    <section className="sm:grid sm:grid-cols-2 min-h-screen">
      <div className="bg-secondary-bg w-full h-screen sm:flex justify-center items-center hidden">
        <div className="w-[70%] ">
          <div className="flex items-center space-x-3 ">
            <div className="bg-gradient-to-r from-blue-900 to-secondary-bg p-3 rounded-xl">
              <LogoSvg className="w-16 h-16" />
            </div>
            <div>
              <Text className="text-sm text-gray-400">Welcome to </Text>
              <h1 className="text-4xl font-bold text-white bg-clip-text">
                Debate Sign Up
              </h1>
              <Text className="text-white mt-1">
                If you already have account?{" "}
                <CustomLink
                  href="/login"
                  className="border-0 p-0 text-blue-500 underline"
                >
                  Login
                </CustomLink>
              </Text>
            </div>
          </div>
          <div className="space-y-6 mt-8 text-white">
            <div className="flex items-center space-x-4">
              <div className="bg-purple-500/20 p-3 rounded-lg">
                <IoPeopleOutline className="h-6 w-6 text-purple-400" />
              </div>
              <div>
                <h3 className="font-semibold text-lg">Join the Community</h3>
                <p className="text-slate-400">
                  Connect with debaters worldwide
                </p>
              </div>
            </div>

            <div className="flex items-center space-x-4">
              <div className="bg-pink-500/20 p-3 rounded-lg">
                <IoTrophyOutline className="h-6 w-6 text-pink-400" />
              </div>
              <div>
                <h3 className="font-semibold text-lg">Compete & Win</h3>
                <p className="text-slate-400">Climb the leaderboards</p>
              </div>
            </div>

            <div className="flex items-center space-x-4">
              <div className="bg-blue-500/20 p-3 rounded-lg">
                <IoChatbubbleEllipsesOutline className="h-6 w-6 text-blue-400" />
              </div>
              <div>
                <h3 className="font-semibold text-lg">Sharpen Your Skills</h3>
                <p className="text-slate-400">Practice with AI and humans</p>
              </div>
            </div>
          </div>
          <ProviderBtns />
        </div>
      </div>
      <div className="h-screen w-full flex sm:flex-row flex-col justify-center items-center">
        {/* <SectionTitle title="Login" className="sm:hidden" /> */}
        <div className="sm:w-[70%] sm:min-h-[400px] w-[320px]">
          <SignupForm />
        </div>
        <ProviderBtns className="flex flex-col p-5 pt-0 mt-0 sm:hidden max-w-[320px]" />
      </div>
    </section>
  );
};

export default SignupPage;
